// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69qGhA8dXQolnqY9XUx3cb7JMgGtz6fg',
    appId: '1:891895880808:web:720eaa8f17e3a6063f2fdd',
    messagingSenderId: '891895880808',
    projectId: 'datingapp-87922',
    authDomain: 'datingapp-87922.firebaseapp.com',
    storageBucket: 'datingapp-87922.firebasestorage.app',
    measurementId: 'G-09QT4XM2V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLL_33SBM08Gw0uB-E6KfEdjNb6LogB_I',
    appId: '1:891895880808:android:1f0c345eb66c29133f2fdd',
    messagingSenderId: '891895880808',
    projectId: 'datingapp-87922',
    storageBucket: 'datingapp-87922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzLI5FVX7REdwXVRV1dChS_KWVhimF15w',
    appId: '1:891895880808:ios:2996b78c6f85b58f3f2fdd',
    messagingSenderId: '891895880808',
    projectId: 'datingapp-87922',
    storageBucket: 'datingapp-87922.firebasestorage.app',
    iosBundleId: 'mido.io.flickr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzLI5FVX7REdwXVRV1dChS_KWVhimF15w',
    appId: '1:891895880808:ios:83e2bba7158d7b863f2fdd',
    messagingSenderId: '891895880808',
    projectId: 'datingapp-87922',
    storageBucket: 'datingapp-87922.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69qGhA8dXQolnqY9XUx3cb7JMgGtz6fg',
    appId: '1:891895880808:web:fad611317a1740bd3f2fdd',
    messagingSenderId: '891895880808',
    projectId: 'datingapp-87922',
    authDomain: 'datingapp-87922.firebaseapp.com',
    storageBucket: 'datingapp-87922.firebasestorage.app',
    measurementId: 'G-1ZQZ5NYMW4',
  );
}
